services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # this is for remote servers because we need
    # to map localhost on the machine to localhost of container
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./node_alerts.yml:/etc/prometheus/node_alerts.yml
      - prometheus_data:/prometheus

    # --config.file: Tells the Prometheus binary exactly where to
    # look for its configuration. We mapped the local prometheus.yml
    # to this internal path in the volumes section, so this command
    # ensures Prometheus actually reads it.

    # --storage.tsdb.path: Defines where the Time Series Database (TSDB)
    # stores the actual data (your historical metrics). We point this to
    # /prometheus because that is where the persistent Docker volume is mounted.
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      # This is for reloading configs easily
      - '--web.enable-lifecycle'
      - '--web.external-url=http://localhost:9090/'
      # This allows k6 to push test result data into prometheus
      # like k6 data
      - '--web.enable-remote-write-receiver'
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      # credentials from .env
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
    networks:
      - monitoring-network

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      # only localhost can access alertmanager
      - "127.0.0.1:9093:9093"
    # Use the config for alertmanager inside this compose file
    # unlike the prometheus config which has it's own file
    # this allows us to use .env variables
    configs:
      - source: alertmanager_config
        target: /etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--web.external-url=http://localhost:9093'
    networks:
      - monitoring-network

  # This monitors the server/machine you're using
  # (my debian)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /run:/run:ro

    # --path.procfs, --path.rootfs, --path.sysfs: By default, Node Exporter
    # looks at /proc and /sys to find CPU and RAM info. Since it's in a container,
    # those folders only show "container" stats. These flags tell it to look at
    # the folders we mounted on the actual machine host instead in volumes section.

    # Exclusion Filter: This is a regex that tells Node Exporter:
    # "Ignore virtual file systems like /dev or /proc when reporting Disk Usage."
    # This keeps your dashboard clean so you only see your actual hard drives
    # (like / or /home) rather than 20 tiny system partitions.
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - monitoring-network

  # cadvisor:
  #   # use the image below instead of 'google/cadvisor:latest'
  #   image: gcr.io/cadvisor/cadvisor:v0.47.0
  #   container_name: cadvisor
  #   restart: unless-stopped
  #   # cAdvisor requires root-level access to the host's kernel information
  #   # to collect container metrics accurately.
  #   privileged: true
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #     - /dev/disk/:/dev/disk:ro
  #   devices:
  #     - /dev/kmsg
  #   ports:
  #     - "8083:8080"
  #   networks:
  #     - monitoring-network

  # Loki: The central storage engine for all logs (The "database" for text logs)
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    # Uses Loki's default internal configuration file
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - monitoring-network

  # Promtail: The log collector that grabs container logs and pushes them to Loki
  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      # Mounts the custom configuration file created in this dir
      - ./promtail-config.yml:/etc/promtail/config.yml
      # Allows Promtail to talk to Docker daemon to read other container logs
      - /var/run/docker.sock:/var/run/docker.sock
      # Optional: Allows Promtail to read system logs from the underlying Debian host
      - /var/log:/var/log
    # Explicitly tells Promtail to read the custom configuration mount
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    depends_on:
      # Ensures Loki starts up completely before Promtail tries to stream logs to it
      - loki
    networks:
      - monitoring-network

  # Tempo: The storage backend for distributed tracing (Maps user request pathways)
  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    volumes:
      # Mounts the custom configuration file created in this dir
      - ./tempo-config.yml:/etc/tempo.yaml
      # persistent storage
      - tempo_data:/var/tempo

    # boot Tempo using the custom config
    # the grafana/tempo image explicitly expects the cleaner Exec Form (Array)
    # to ensure it never drops traces during a reboot.
    command: [ "--config.file=/etc/tempo.yaml" ]
    ports:
      # the '127.0.0.1' Explicitly binds port 4318 to your host's localhost
      # Tempo's web API port (Grafana uses this to fetch and display traces)
      - "127.0.0.1:3200:3200"
      # OTLP gRPC ingest (Your Spring Boot app can send traces here)
      - "127.0.0.1:4317:4317"
      # OTLP HTTP ingest port. Alternative endpoint for apps utilizing HTTP-based tracing.
      - "127.0.0.1:4318:4318"
    restart: unless-stopped
    networks:
      - monitoring-network

  # Blackbox Exporter: Turns Prometheus into an external HTTP prober
  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    restart: unless-stopped
    ports:
      - "127.0.0.1:9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    networks:
      - monitoring-network


  sonarqube-db:
    image: postgres:16-alpine
    container_name: sonarqube-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
    networks:
      - monitoring-network

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: unless-stopped
    depends_on:
      - sonarqube-db
    environment:
      - SONAR_JDBC_USERNAME=${SONAR_JDBC_USERNAME}
      - SONAR_JDBC_PASSWORD=${SONAR_JDBC_PASSWORD}
      - SONAR_JDBC_URL=${SONAR_JDBC_URL}
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ulimits:
      # 'nofile (Number of Open Files)', It tells the Linux kernel how many system
      # file descriptors (which include open files, network sockets, and pipes) this
      # specific container is allowed to keep open at the exact same time.
      nofile:
        # soft cap (minimum), default is 1024 which is too low for Elasticsearch
        soft: 65536
        # hard cap (max), Setting both soft and hard to 65536 locks the configuration
        # in place, ensuring SonarQube always has an abundant, stable pool of file
        # allocations to handle large codebases.
        hard: 65536
    deploy:
      resources:
        # Tells Docker that if SonarQube tries to consume more than 2.5GB of RAM,
        # throttle it immediately so the host stays completely stable.
        limits:
          memory: 2.5G
        # Tells Docker to guarantee SonarQube has 1.5GB to start up comfortably.
        reservations:
          memory: 1.5G
    networks:
      - monitoring-network


volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  tempo_data:
  sonarqube_db_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

# explicitly define a network and tie Grafana, Loki, and Tempo
# directly to it so they can see each other instantly.
networks:
  monitoring-network:
    driver: bridge

# config for alertmanager
configs:
  alertmanager_config:
    content: |
      global:
        resolve_timeout: 5m

      route:
        group_by: ['alertname', 'instance']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        receiver: 'gmail-notifications'

      receivers:
      - name: 'gmail-notifications'
        email_configs:
        - to: '${GMAIL}'
          from: '${GMAIL}'
          smarthost: 'smtp.gmail.com:587'
          auth_username: '${GMAIL}'
          auth_password: '${GMAIL_PASS}'
          auth_identity: '${GMAIL}'
          send_resolved: true