# This configuration file tells Prometheus how often to collect data
# and where to find it. Without this, Prometheus is just
# an empty database with no data flowing in.

# global:: These settings apply to every data source Prometheus
# tracks unless you override them specifically for a single job.
global:
  # This is the heartbeat. It tells Prometheus to "pull" (scrape)
  # new data from your targets every 15 seconds.
  # - Lowering it (e.g., 5s) gives higher resolution but uses more disk space.
  # - Raising it (e.g., 1m) saves space but makes your graphs look "blocky."
  scrape_interval: 15s

# Tell Prometheus to read the alerts file inside its internal directory
rule_files:
  - "/etc/prometheus/node_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # uses docker's internal network DNS name
            - 'alertmanager:9093'

# This is the start of the list of "targets" or services you want to monitor.
# Think of this as the "Address Book" for Prometheus.
scrape_configs:

    # Job 1: Self-Monitoring
    # job_name: 'prometheus': A label used to group the data.
    # In Grafana, you can filter metrics by this name.
  - job_name: 'prometheus'
    # Tells Prometheus that these addresses are hard-coded
    # and won't change (as opposed to "Service Discovery"
    # where addresses are found automatically).
    static_configs:
        # Prometheus is monitoring itself. It exposes its own performance
        # metrics (like memory usage and how many samples it's ingesting) on port 9090.
      - targets: ['localhost:9090']

    # Job 2: The Server Metrics (Node Exporter)
    # job_name: 'node': Usually refers to "Node Exporter,"
    # the tool that looks at the physical (or virtual) machine.
  - job_name: 'node'
    static_configs:
        # node-exporter: This matches the service name you wrote in your
        # docker-compose.yml. Docker acts as a DNS server and translates
        # this name to the correct internal IP address.
        # 9100: The default port where Node Exporter shares hardware stats (CPU, RAM, Disk).
      - targets: ['node-exporter:9100']

  # - job_name: 'cadvisor'
  #   static_configs:
  #     # Use the INTERNAL port (8080), not the mapped host port (8081)
  #     - targets: ['cadvisor:8080']

  - job_name: 'spring-boot-demo-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.108:8081']

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        # Pings the SonarQube web portal port on your machine
        - http://sonarqube:9000
        - https://ibrahimmoalim.dev
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Monitor remote servers
  # - job_name: 'remote-servers-via-ssh'
  #   static_configs:
  #     - targets: ['host.docker.internal:9101']
  #       # labels are important so we can see which server is being monitored on 9101
  #       labels:
  #         instance: 'aws-ec2-production'
  #         provider: 'aws'
  #     # - targets: ['localhost:9102']
  #     #   labels:
  #     #     instance: 'linode-web-server'
  #     #     provider: 'linode'
